dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

before_install:
  - pip install --upgrade pip
  - pip install coveralls

install:
  - "pip install -r requirements.txt --progress-bar=off"
  - "pip install -r requirements/pandas.txt --progress-bar=off"
  - "pip install -r requirements/dask.txt --progress-bar=off"

script:
  - python -m unittest