{% set version = "3.0.0" %}

package:
  name: optimus
  version: {{ version }}

source:
  git_url: https://github.com/hi-primus/optimus
  git_rev: develop-3.0
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - simplejson            3.16.0
    - cryptography          2.7
    - packaging             19.1
    - requests              2.20.0
    - tqdm                  4.28.1
    - fastnumbers           3.0.0
    - multipledispatch      0.6.0
    - matplotlib            3.0.3
    - seaborn               0.9.0
    - deprecated            1.2.5
    - setuptools            41.6.0
    - Jinja2                2.10.1
    - tensorflow            1.13.1
    - keras                 2.2.4
    - pygments              2.2.0
    - ipython               7.5.0
    - humanize              0.5.1
    - psutil                5.6.3
    - pandas                1.0.5
    - ordered-set           3.1.1
    - deepdiff              4.0.6
    - statsmodels           0.10.1
    - glom                  19.10.0
    - nltk                  3.4.5
    - fastavro              0.22.7
    - rapids                0.15
    - cudatoolkit           10.1
    - blosc                 1.9.2
    - lz4                   3.1.0

about:
  home: https://github.com/hi-primus/pyoptimus
  license: MIT
  summary: 'Agile Data Science Workflows made easy with Pyspark, Dask, cuDF, and dask-cuDF'
  description: Agile Data Science Workflows made easy with Pyspark, Dask, cuDF, and dask-cuDF
  dev_url: https://github.com/hi-primus/optimus
  doc_url: https://pypi.python.org/pypi/pyoptimus
  doc_source_url: https://github.com/hi-primus/pyoptimus/blob/master/README.rst