name: Publish to Test PyPI

on:
  push:
    tags:
      - 'test-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Configure Poetry
        run: |
          poetry config repositories.pyoptimus https://test.pypi.org/legacy/
          poetry config http-basic.pyoptimus ${{ secrets.TEST_PYPI_USERNAME }} ${{ secrets.TEST_PYPI_PASSWORD }}
      - name: Build and publish package
        run: |
          TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\///')
          echo "Tag (not used): $TAG_NAME"
          poetry build
          poetry publish -r pyoptimus
        env:
          TEST_PYPI_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}